#!/usr/bin/env python

import argparse
import os
from datetime import datetime
import mechanize
from BeautifulSoup import BeautifulSoup

GITHUB_URL = 'https://github.com'

def download_pdf(url, filename, bill_date, br):
    if os.path.isdir(filename):
        br.open(url)
        handler = open(filename + '/Github - ' + str(bill_date) + '.pdf', 'wb')
        handler.write(br.response().read())
        handler.close()

def main():
    br = mechanize.Browser()
    br.set_handle_robots(False)
    br.open(GITHUB_URL + '/account/receipts')

    br.select_form(nr=0)
    br.form['login'] = args.username
    br.form['password'] = args.password
    br.submit()
    html = br.response().read()

    soup = BeautifulSoup(html)

    tds = soup.findAll('tr')[1].findAll('td')
    url = GITHUB_URL + tds[2].a['href']

    bill_date = datetime.strptime(tds[0].text, '%Y-%m-%d').date()
    download_pdf(url, args.directory, bill_date, br)

parser = argparse.ArgumentParser(description='Download your latest github receipt.')
parser.add_argument('--username', type=str, required=True, help='Github username')
parser.add_argument('--password', type=str, required=True, help='Github password')
parser.add_argument(
    '-d', '--directory', type=str, help='Directory to download pdf', default='.'
)

args = parser.parse_args()
if __name__ == "__main__":
    main()
