#!/usr/bin/env python

import argparse
import os
from datetime import datetime
from mechanize import Browser
from BeautifulSoup import BeautifulSoup

GITHUB_URL = 'https://github.com'

def download_pdf(url, filename, bill_date, browser):
    """Save PDF to disk"""
    if os.path.isdir(filename):
        browser.open(url)
        path = '{filename}/github - {date}.pdf'.format(filename=filename, date=str(bill_date))
        with open(path, 'wb') as handler:
            handler.write(browser.response().read())

def main():
    """Main"""
    parser = argparse.ArgumentParser(description='Download your latest github receipt.')
    parser.add_argument('--username', type=str, required=True, help='Github username')
    parser.add_argument('--password', type=str, required=True, help='Github password')
    parser.add_argument(
        '-d', '--directory', type=str, help='Directory to download pdf', default='.'
    )

    args = parser.parse_args()

    browser = Browser()
    browser.set_handle_robots(False)
    browser.open(GITHUB_URL + '/account/receipts')

    browser.select_form(nr=0)
    browser.form['login'] = args.username
    browser.form['password'] = args.password
    browser.submit()
    html = browser.response().read()

    soup = BeautifulSoup(html)

    tds = soup.findAll('tr')[1].findAll('td')
    url = GITHUB_URL + tds[2].a['href']

    bill_date = datetime.strptime(tds[0].text, '%Y-%m-%d').date()
    download_pdf(url, args.directory, bill_date, browser)

if __name__ == "__main__":
    main()
